kind: "List"
apiVersion: "v1"
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: elasticsearch
    namespace: default
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: Role
  metadata:
    name: elasticsearch
    namespace: default
  rules:
  - apiGroups:
    - ""
    resources:
    - endpoints
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1beta1
  kind: RoleBinding
  metadata:
    name: elasticsearch
    namespace: default
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: elasticsearch
  subjects:
  - kind: ServiceAccount
    name: elasticsearch
    namespace: default