cluster.name: ${CLUSTER_NAME}
network.host: ${NETWORK_HOST}

# Cluster Setting
node.master: ${NODE_MASTER}
node.data: ${NODE_DATA}
node.ingest: ${NODE_INGEST}
search.remote.connect: false

discovery.zen.minimum_master_nodes: ${NUMBER_OF_MASTERS}
xpack.license.self_generated.type: basic