apiVersion: extensions/v1beta1
kind: "Service"
metadata:
  name: "elasticsearch-cluster"
spec:
  clusterIP: "None"
  ports:
    - port: 9300
      targetPort: 9300
  selector:
    provider: "fabric8"
    component: "elasticsearch"