kind: Service
apiVersion: v1
metadata:
  name: "elasticsearch"
spec:
  selector:
    app: "elasticsearch"
  ports:
    - protocol: "TCP"
      port: 9200
      targetPort: 9200
      nodePort: 30001
  type: NodePort
