apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
        role: master
        version: 6.4.2
    spec:
      initContainers:
      - name: init-pod
        image: busybox:1.27.2
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: "gcr.io/gcp-summit-2018/elasticsearch:6.4.2"
        ports:
        - name: es-external
          containerPort: 9200
          hostPort: 9200
        - name: transport
          containerPort: 9300
          hostPort: 9300
        env:
        - name: CLUSTER_NAME
          value: gcp-summit-es
        - name: NUMBER_OF_MASTERS
          value: "1"
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          value: "false"
        - name: NODE_DATA
          value: "false"
        - name: NETWORK_HOST
          value: "0.0.0.0"
        - name: ES_JAVA_OPTS
          value: -Xms256m -Xmx256m
        readinessProbe:
          httpGet:
            path: /
            port: 9200
          initialDelaySeconds: 10
          periodSeconds: 15
          timeoutSeconds: 5